name: Pull Request Template
description: Template for submitting pull requests to the project

body:
    - type: checkboxes
      id: types_of_changes
      attributes:
          label: Types of changes
          description: |
              What types of changes does your code introduce? Put an `x` in all the boxes that apply:

      options:
          - label: **New feature** (prefix: `feat` - non-breaking change which adds functionality)
            description: Link to the issue or discussion where this has been agreed with a maintainer. **WARNING: If the link is absent, the PR may be closed without review**, due to the workload that such reviews usually require.
            required: true
          - label: **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)
            description: Link to the issue or discussion where this has been agreed with a maintainer.
            required: true
          - label: **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
          - label: **Documentation** (prefix: `docs` - improvements to any documentation content **for users**)
          - label: **Sample vault** (prefix: `vault` - improvements to the [Tasks-Demo sample vault](https://github.com/obsidian-tasks-group/obsidian-tasks/tree/main/resources/sample_vaults/Tasks-Demo))
          - label: **Contributing Guidelines** (prefix: `contrib` - any improvements to documentation content **for contributors** - see [Contributing to Tasks](https://publish.obsidian.md/tasks-contributing/))
          - label: **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
          - label: **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
          - label: **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

    - type: markdown
      id: description
      attributes:
          value: |
              ## Description
              <!--- Remember to provide a general summary of your changes in the Title above -->
              <!--- Describe your changes in detail -->

    - type: markdown
      id: motivation_and_context
      attributes:
          value: |
              ## Motivation and Context
              <!--- Why is this change required? What problem does it solve? -->
              <!--- If it fixes an open issue, please link to the issue here. -->

    - type: markdown
      id: how_has_this_been_tested
      attributes:
          value: |
              ## How has this been tested?
              <!--- Please describe in detail how you tested your changes. -->
              <!--- Include details of your testing environment, tests ran to see how -->
              <!--- your change affects other areas of the code, etc. -->

    - type: markdown
      id: screenshots
      attributes:
          value: |
              ## Screenshots (if appropriate)

    - type: checkboxes
      id: checklist
      attributes:
          label: Checklist
          description: |
              Go over all the following points, and put an `x` in all the boxes that apply.
              If you're unsure about any of these, don't hesitate to ask. We're here to help!
      options:
          - label: My code follows the code style of this project and passes `yarn run lint`.
          - label: My change requires a change to the documentation.
          - label: I have [updated the documentation](https://publish.obsidian.md/tasks-contributing/Documentation/About+Documentation) accordingly.
          - label: My change has adequate [Unit Test coverage](https://publish.obsidian.md/tasks-contributing/Testing/About+Testing).

    - type: checkboxes
      id: terms
      attributes:
          label: Terms
          description: |
              By submitting this pull request, you must agree to follow our
              [contributing guide](https://publish.obsidian.md/tasks-contributing) and
              [Code of Conduct](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CODE_OF_CONDUCT.md).
              Put an x in the boxes to confirm you agree.
      options:
          - label: My contribution follows this project's [contributing guide](https://publish.obsidian.md/tasks-contributing)
          - label: I agree to follow this project's [Code of Conduct](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CODE_OF_CONDUCT.md)
